# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: true
sudo: required
cache: packages
dist: trusty

before_install:
  - git lfs pull

script: 
  - R -f tests/render_rmds.R
  - df -h