# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: true
sudo: required
cache: packages
dist: trusty

addons:
  apt:
    packages:
      - libudunits2-dev
      - libproj-dev 
      - libgeos-dev
      - libgdal-dev 
      - libgsl-dev

before_install:
  - git lfs pull

script: 
  - R -f tests/render_rmds.R
  - df -h