---
title: "final_project_dag"
author: "Stephen Antonoplis"
date: "4/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggdag)
```

```{r, Version 1 (me alone without Katie)}
# Version 1 (me alone without Katie)
model1 <- dagify(ScoreThreshhold ~ PM2.5 + Absenteeism + Suspension + MinorityEnrollment + FreeLunch + AirBasin,
                Absenteeism ~ PM2.5 + Suspension + FreeLunch + AirBasin + MinorityEnrollment,
                Suspension ~ PM2.5 + FreeLunch + AirBasin + MinorityEnrollment,
                PM2.5 ~ AirBasin + FreeLunch + MinorityEnrollment,
                FreeLunch ~ MinorityEnrollment,
                exposure='PM2.5',outcome='ScoreThreshhold',
                coords=list(x=c(ScoreThreshhold=1,PM2.5=-2,MinorityEnrollment=-2,FreeLunch=-1,AirBasin=0,
                                Suspension=-1,Absenteeism=-0.5),
                            y=c(ScoreThreshhold=-2,PM2.5=-0.5,MinorityEnrollment=2,FreeLunch=1.5,AirBasin=2,
                                Suspension=-2,Absenteeism=-1.5))
                )
ggdag(model1,node=FALSE,text_col='black')
ggdag_adjustment_set(model1,text_col='black')
```

```{r, Version 2 (after talking to Katie)}
# Version 2 (after talking to Katie)
  # construction rules:
  # - observed indicators entered into equations before unobserved indicators
  # - observed indicators grouped on separate line from unobserved indicators
  # - after adding an unobserved indicator to an equation, immediately add it to the "latent" parameter before altering further equations
  # - enter only *direct* causes of a variable into its equation
  # - make equations for observed variables first, then for unobserved variables
  # - enter associations between variables on the line following the equation for the variable and indented
  # - observed variables = PM2.5, Scores, Absenteeism, Suspension, FreeLunch, MinorityPerc, ESL, AirBasin, PerCapEduFund
model2 <- dagify(PM2.5 ~ PolicyInfluence + LandUsePolicy + GeoFeat + AirPolicy,
                Scores ~ PM2.5 + Absenteeism + Suspension + FreeLunch + ESL + AirBasin + PerCapEduFund +
                         TeacherDiscrim + TeacherQual,
                Absenteeism ~ PM2.5 + Suspension,
                Suspension ~ PM2.5 + 
                             TeacherDiscrim,
                FreeLunch ~ HouseIncome,
                MinorityPerc ~ LandUsePolicy,
                ESL ~ FamSpeakEng,
                AirBasin ~ GeoFeat,
                PerCapEduFund ~ LandUsePolicy + LocalPropertyTax,
                
                PolicyInfluence ~ MinorityPerc + 
                                  FamSpeakEng + HouseIncome,
                #LandUsePolicy ~ ,
                #GeoFeat ~ ,
                AirPolicy ~ AirBasin,
                TeacherDiscrim ~ MinorityPerc,
                TeacherQual ~ PerCapEduFund,
                HouseIncome ~ MinorityPerc + LandUsePolicy + FamSpeakEng,
                FamSpeakEng ~ MinorityPerc,
                LocalPropertyTax ~ HouseIncome,
                exposure="PM2.5",outcome="Scores",
                latent=c("PolicyInfluence","LandUsePolicy","GeoFeat","AirPolicy","TeacherDiscrim","TeacherQual","HouseIncome","FamSpeakEng","LocalPropertyTax"),
                coords=list(x=c(PM2.5=-5,Scores=4,Absenteeism=-1.5,Suspension=-2,FreeLunch=2,MinorityPerc=-5,ESL=2,AirBasin=-1,PerCapEduFund=3.5,
                                PolicyInfluence=-5,LandUsePolicy=0,GeoFeat=-2.6,AirPolicy=-2.35,TeacherDiscrim=.75,TeacherQual=3.75,HouseIncome=0,FamSpeakEng=1,LocalPropertyTax=1.25),
                            y=c(PM2.5=-0.5,Scores=-2,Absenteeism=-1.5,Suspension=-2.5,FreeLunch=1,MinorityPerc=5,ESL=3.5,AirBasin=0.75,PerCapEduFund=4,
                                PolicyInfluence=3,LandUsePolicy=6,GeoFeat=0,AirPolicy=-0.25,TeacherDiscrim=0.25,TeacherQual=3,HouseIncome=1.5,FamSpeakEng=4.25,LocalPropertyTax=2.25))
                )
ggdag(model2,node=FALSE,text_col="black")
ggdag_adjustment_set(model2,text_col="black")
```

```{r, Version 3 (beautifying Version 2)}
# Version 3 (beautifying Version 2)
  # construction rules:
  # - observed indicators entered into equations before unobserved indicators
  # - observed indicators grouped on separate line from unobserved indicators
  # - after adding an unobserved indicator to an equation, immediately add it to the "latent" parameter before altering further equations
  # - enter only *direct* causes of a variable into its equation
  # - make equations for observed variables first, then for unobserved variables
  # - enter associations between variables on the line following the equation for the variable and indented
  # - observed variables = PM2.5, Scores, Absenteeism, Suspension, FreeLunch, MinorityPerc, ESL, AirBasin, PerCapEduFund
model3 <- dagify(PM2.5 ~ PolicyInfluence + LandUsePolicy + GeoFeat + AirPolicy,
                Scores ~ PM2.5 + Absenteeism + Suspension + FreeLunch + ESL + AirBasin + PerCapEduFund +
                         TeacherDiscrim + TeacherQual,
                Absenteeism ~ PM2.5 + Suspension,
                Suspension ~ PM2.5 + 
                             TeacherDiscrim,
                FreeLunch ~ HouseIncome,
                MinorityPerc ~ LandUsePolicy,
                ESL ~ FamSpeakEng,
                AirBasin ~ GeoFeat,
                PerCapEduFund ~ LandUsePolicy + LocalPropertyTax,
                
                PolicyInfluence ~ MinorityPerc + 
                                  FamSpeakEng + HouseIncome,
                #LandUsePolicy ~ ,
                #GeoFeat ~ ,
                AirPolicy ~ AirBasin,
                TeacherDiscrim ~ MinorityPerc,
                TeacherQual ~ PerCapEduFund,
                HouseIncome ~ MinorityPerc + LandUsePolicy + FamSpeakEng,
                FamSpeakEng ~ MinorityPerc,
                LocalPropertyTax ~ HouseIncome,
                exposure="PM2.5",outcome="Scores",
                latent=c("PolicyInfluence","LandUsePolicy","GeoFeat","AirPolicy","TeacherDiscrim","TeacherQual","HouseIncome","FamSpeakEng","LocalPropertyTax"),
                coords=list(x=c(PM2.5=-5,Scores=4,Absenteeism=-1.5,Suspension=-2,FreeLunch=1.75,MinorityPerc=-5,ESL=2,AirBasin=-2.35,PerCapEduFund=3.5,
                                PolicyInfluence=-5,LandUsePolicy=-1,GeoFeat=-3,AirPolicy=-2.75,TeacherDiscrim=0,TeacherQual=3.75,HouseIncome=0.75,FamSpeakEng=1,LocalPropertyTax=1.75),
                            y=c(PM2.5=-0.5,Scores=-2,Absenteeism=-1.5,Suspension=-2.5,FreeLunch=0.8,MinorityPerc=5,ESL=3.5,AirBasin=0.75,PerCapEduFund=4,
                                PolicyInfluence=4,LandUsePolicy=6,GeoFeat=0,AirPolicy=-0.25,TeacherDiscrim=0.25,TeacherQual=3,HouseIncome=1.3,FamSpeakEng=4.25,LocalPropertyTax=2.05))
                )
ggdag(model3,node=FALSE,text_col="black")
ggdag_adjustment_set(model3,text_col="black")
```

```{r, Version 4 (updating Version 3)}
# Version 4 (updating Version 3)
  # construction rules:
  # - observed indicators entered into equations before unobserved indicators
  # - observed indicators grouped on separate line from unobserved indicators
  # - after adding an unobserved indicator to an equation, immediately add it to the "latent" parameter before altering further equations
  # - enter only *direct* causes of a variable into its equation
  # - make equations for observed variables first, then for unobserved variables
  # - enter associations between variables on the line following the equation for the variable and indented
  # - observed variables = PM2.5, Scores, Absenteeism, Suspension, FreeLunch, MinorityPerc, ESL, AirBasin, PerCapEduFund
model4 <- dagify(PM2.5 ~ SchoolEnroll +
                         PolicyInfluence + LandUsePolicy + GeoFeat + AirPolicy,
                MathScores ~ PM2.5 + Absenteeism + Suspension + FreeLunch + ESL + AirBasin + PerCapEduFund + StuTeachRatio +
                             TeacherDiscrim + TeacherQual + SchoolEnroll,
                Absenteeism ~ PM2.5 + Suspension,
                Suspension ~ PM2.5 + 
                             TeacherDiscrim,
                FreeLunch ~ HouseIncome,
                PoCPerc ~ LandUsePolicy,
                ESL ~ FamSpeakEng,
                AirBasin ~ GeoFeat,
                PerCapEduFund ~ FreeLunch + 
                                LandUsePolicy + LocalPropertyTax,
                StuTeachRatio ~ SchoolEnroll + HouseWealth + HouseIncome,
                SchoolEnroll ~ LandUsePolicy,
                TeacherQual ~ PerCapEduFund + 
                              LandUsePolicy + HouseIncome,
                
                PolicyInfluence ~ PoCPerc + 
                                  FamSpeakEng + HouseIncome,
                #LandUsePolicy ~ ,
                #GeoFeat ~ ,
                AirPolicy ~ AirBasin,
                TeacherDiscrim ~ PoCPerc,
                HouseIncome ~ PoCPerc + LandUsePolicy + FamSpeakEng,
                HouseWealth ~ PoCPerc + LandUsePolicy + FamSpeakEng,
                FamSpeakEng ~ PoCPerc,
                LocalPropertyTax ~ HouseIncome + HouseWealth,
                exposure="PM2.5",outcome="MathScores",
                latent=c("PolicyInfluence","LandUsePolicy","GeoFeat","AirPolicy","TeacherDiscrim","HouseIncome","FamSpeakEng","LocalPropertyTax","HouseWealth"),
                coords=list(x=c(PM2.5=-5,MathScores=4,Absenteeism=-1.5,Suspension=-2,FreeLunch=1.75,PoCPerc=-5,ESL=2,AirBasin=-2.35,PerCapEduFund=3.5,StuTeachRatio=-3,SchoolEnroll=-2.75,TeacherQual=3.75,
                                PolicyInfluence=-5,LandUsePolicy=-1,GeoFeat=-3,AirPolicy=-2.75,TeacherDiscrim=0,HouseIncome=0.75,FamSpeakEng=1,LocalPropertyTax=1.75,HouseWealth=0),
                            y=c(PM2.5=-0.5,MathScores=-2,Absenteeism=-1.5,Suspension=-2.5,FreeLunch=0.8,PoCPerc=5,ESL=3.5,AirBasin=0.75,PerCapEduFund=4,StuTeachRatio=1.4,SchoolEnroll=2.2,TeacherQual=3,
                                PolicyInfluence=4,LandUsePolicy=6,GeoFeat=0,AirPolicy=-0.25,TeacherDiscrim=0.25,HouseIncome=1.3,FamSpeakEng=4.25,LocalPropertyTax=2.05,HouseWealth=2.5))
                )
ggdag(model4,node=FALSE,text_col="black")
ggdag_adjustment_set(model4,text_col="black")
```

```{r, Practice to see how ggdag handles Us}
model_u <- dagify(Y ~ A + W + U_y,
                  A ~ W + U_a,
                  W ~ U_w,
                  U_y ~~ U_a + U_w,
                  U_a ~~ U_w,
                  exposure="A",outcome="Y",
                  #latent=c("U_a","U_y","U_w"),
                  coords=list(x=c(A=-1,Y=1,W=0,U_a=-1.5,U_y=1.5,U_w=0),
                              y=c(A=0,Y=0,W=1.5,U_a=-0.5,U_y=-0.5,U_w=2)))
ggdag(model_u)
ggdag_adjustment_set(model_u)
```

```{r, Version 5 (add global U to Version 4)}
model5 <- dagify(PM2.5 ~ SchoolEnrollment +
                         LocalPolicyInfluence + LandUsePolicy + GeoFeatures + AirPolicy,
                MathScores ~ PM2.5 + Absenteeism + Suspension + FreeReducedLunch + EnglishLearnerPercent + AirBasin + PerCapEduFund + StudentTeacherRatio +
                             TeacherDiscrimination + TeacherQuality + SchoolEnrollment,
                Absenteeism ~ PM2.5 + Suspension,
                Suspension ~ PM2.5 + 
                             TeacherDiscrimination,
                FreeReducedLunch ~ LocalHouseIncome,
                PoCEnrollment ~ LandUsePolicy,
                EnglishLearnerPercent ~ LocalFamiliesSpeakEnglish,
                AirBasin ~ GeoFeatures,
                PerCapEduFund ~ FreeReducedLunch + 
                                LandUsePolicy + LocalPropertyTax,
                StudentTeacherRatio ~ SchoolEnrollment + LocalHouseWealth + LocalHouseIncome,
                SchoolEnrollment ~ LandUsePolicy,
                TeacherQuality ~ PerCapEduFund + 
                                 LandUsePolicy + LocalHouseIncome,
                
                LocalPolicyInfluence ~ PoCEnrollment + 
                                      LocalFamiliesSpeakEnglish + LocalHouseIncome,
                #LandUsePolicy ~ ,
                #GeoFeatures ~ ,
                AirPolicy ~ AirBasin,
                TeacherDiscrimination ~ PoCEnrollment,
                LocalHouseIncome ~ PoCEnrollment + LandUsePolicy + LocalFamiliesSpeakEnglish,
                LocalHouseWealth ~ PoCEnrollment + LandUsePolicy + LocalFamiliesSpeakEnglish,
                LocalFamiliesSpeakEnglish ~ PoCEnrollment,
                LocalPropertyTax ~ LocalHouseIncome + LocalHouseWealth,
                exposure="PM2.5",outcome="MathScores",
                latent=c("LocalPolicyInfluence","LandUsePolicy","GeoFeatures","AirPolicy","TeacherDiscrimination","LocalHouseIncome",
                         "LocalFamiliesSpeakEnglish","LocalPropertyTax","LocalHouseWealth"),
                coords=list(x=c(PM2.5=-5,MathScores=4,Absenteeism=-1.5,Suspension=-2,FreeReducedLunch=1.75,PoCEnrollment=-5,EnglishLearnerPercent=2,AirBasin=-2.35,
                                PerCapEduFund=3.5,StudentTeacherRatio=-3,SchoolEnrollment=-2.75,TeacherQuality=3.75,
                                LocalPolicyInfluence=-5,LandUsePolicy=-1,GeoFeatures=-3,AirPolicy=-2.75,TeacherDiscrimination=0,LocalHouseIncome=0.75,
                                LocalFamiliesSpeakEnglish=1,LocalPropertyTax=1.75,LocalHouseWealth=0),
                            y=c(PM2.5=-0.5,MathScores=-2,Absenteeism=-1.5,Suspension=-2.5,FreeReducedLunch=0.8,PoCEnrollment=5,EnglishLearnerPercent=3.5,AirBasin=0.75,
                                PerCapEduFund=4,StudentTeacherRatio=1.4,SchoolEnrollment=2.2,TeacherQuality=3,
                                LocalPolicyInfluence=4,LandUsePolicy=6,GeoFeatures=0,AirPolicy=-0.25,TeacherDiscrimination=0.25,LocalHouseIncome=1.3,
                                LocalFamiliesSpeakEnglish=4.25,LocalPropertyTax=2.05,LocalHouseWealth=2.5))
                )
m5 <- ggdag(model5,node=FALSE,text_col="black") +
  theme(axis.text.x = element_blank(), axis.ticks = element_blank(), axis.line.x = element_blank()) +
  theme(axis.text.y = element_blank(), axis.ticks = element_blank(), axis.line.y = element_blank()) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme(panel.background = element_blank()) +
  labs(x="",y="")
m5

m5_adj <- ggdag_adjustment_set(model5,text_col="black") +
  theme(axis.text.x = element_blank(), axis.ticks = element_blank(), axis.line.x = element_blank()) +
  theme(axis.text.y = element_blank(), axis.ticks = element_blank(), axis.line.y = element_blank()) +
  theme(strip.background = element_blank(), strip.text.x = element_blank()) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme(panel.background = element_blank()) +
  labs(x="",y="")
m5_adj

```

