---
title: "Untitled"
author: "Katherine Rose Wolf"
date: "August 19, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r read school primary short enrollment data files, eval=FALSE, include=FALSE}

# make school primary short data file downloader function
school_primary_short_enrollment_raw_downloader <-
  function(start_year_numeric){
    end_year_chr <- 
      as.character(start_year_numeric + 1) %>%  # add 1 to the start year
      substr(3, 4)  # get only the last two digits
    
    start_year_chr <- 
      as.character(start_year_numeric) %>%   # convert start year to numeric
      substr(3, 4)  # get only the last two digits
    
    start_year_chr_long <- 
      as.character(start_year_numeric)
    
    url_file <- 
      str_c(
        "http://dq.cde.ca.gov/dataquest/dlfile/dlfile.aspx?cLevel=School&cYear=", 
        start_year_chr, 
        end_year_chr, 
        "&cCat=ShortTermEnrl&cPage=filesenrps.asp"
        )
            download.file(
      url = url_file, 
      destfile = 
        file.path(
          "raw_data", 
          str_c("school_primary_short_enrollment_", 
                start_year_chr_long,
                "_", 
                end_year_chr, 
                "_raw.txt")
        )
    )
  }

# make vector of starting years 2009-2018
start_years <- 
  seq(
    from = 2009,
    to = 2018, 
    by = 1
  )

# download all the school files at once
map(
  .f = school_primary_short_enrollment_raw_downloader, 
  .x = start_years
)

# make function to read them all into r from tab-delimited files
school_primary_short_enrollment_tab_reader <- 
  function(start_year_numeric){
    
    end_year_chr <- 
      as.character(start_year_numeric + 1) %>% 
      substr(3, 4)  # get only the last two digits
    
    start_year_chr <- 
      as.character(start_year_numeric)
    
    file_name <- 
      str_c("school_primary_short_enrollment_", 
            start_year_chr, 
            "_", 
            end_year_chr, 
            "_raw.txt")
      
    variable_name <- 
      str_c("school_primary_short_enrollment_", 
            start_year_chr, 
            "_", 
            end_year_chr, 
            "_working")
    
    read_tibble <- 
      read_delim(
        file = 
          file.path(
            "raw_data", 
            file_name),
        delim = "\t"
        )
    
    assign(variable_name, 
           read_tibble)
    
    save(
      list = variable_name, 
      file = 
        file.path(
          "intermediate_data", 
          str_c(
            variable_name, 
            ".rdata"
          )
        )
    )
    
    # return(read_tibble)
  }

# use function on all files
map(
  .f = school_primary_short_enrollment_tab_reader, 
  .x = start_years
)


```


```{r download raw 2017 facility emissions data, eval=FALSE, include=FALSE}

# download raw emissions csv file
download.file(
  url = "https://www.arb.ca.gov/app/emsinv/facinfo/faccrit_output.csv?&dbyr=2017&ab_=&dis_=&co_=&fname_=&city_=&sort=FacilityNameA&fzip_=&fsic_=&facid_=&all_fac=&chapis_only=&CERR=&dd=", 
  destfile = 
    file.path(
      "raw_data", 
      "facility_emissions_2017.csv"
    )
  )

facility_emissions_2017 <- 
  read_csv(file = 
             file.path(
               "raw_data",
               "facility_emissions_2017.csv"
               ), 
           col_types = 
             cols(CO = col_double(),
                  AB = col_character(),
                  FACID = col_double(),
                  DIS = col_character(),
                  FNAME = col_character(),
                  FSTREET = col_character(),
                  FCITY = col_character(),
                  FZIP = col_character(),
                  FSIC = col_double(),
                  COID = col_character(),
                  DISN = col_character(),
                  CHAPIS = col_character(),
                  CERR_CODE = col_character(),
                  TOGT = col_double(),
                  ROGT = col_double(),
                  COT = col_double(),
                  NOXT = col_double(),
                  SOXT = col_double(),
                  PMT = col_double(),
                  PM10T = col_double()))

# note: cannot read mapping file manually
facility_emissions_2017_mapping <- 
  read_csv(
    file = 
      file.path(
        "raw_data",
        "EmissionsByFacility.csv"
        ), 
    col_types = "cccccccccccccccccccccccccccccccccccccc"
    )

save(facility_emissions_2017_mapping, 
     file = 
       file.path(
         "intermediate_data", 
         "facility_emissions_2017_mapping.rdata"
       )
     )

colnames(facility_emissions_2017_mapping)

facility_emissions_2017_pm25 <- 
  facility_emissions_2017_mapping %>% 
  filter(!is.na(PM2.5))

nrow(facility_emissions_2017_pm25)

# facility_emissions_2017_mapping <- 
#   facility_emissions_2017_mapping %>% 
   

```


```{r raster data}

# plot(asc_air_data)
# crs(asc_air_data)
# 
# getValues(asc_air_data, 
#           row = 1, 
#           nrows = 1)

```



```{r plot in once place}

load(
  file = 
    file.path(
      "intermediate_data", 
      "carb_pm25_sf.rdata"
    )
)

load(
  file = 
    file.path(
      "intermediate_data", 
      "cal_epa_monitors_sf.rdata"
    )
)

load(
  file = 
    file.path(
      "intermediate_data", 
      "air_cropped.rdata"
    )
)



plot(air_cropped)
plot(carb_pm25_sf)
plot(cal_epa_monitors_sf)

# remove all objects from the environment
rm(list = ls(all.names = TRUE))

```


```{r}

# # two without lat/long
# ## Gateway to College, San Francisco Unified, 50 Phelan Avenue Science Hall, Room 127, San Francisco, CA 94112-1821
# ### manually found lat/long via Google Maps: 37.724958, -122.452911
# ## Academy of Arts and Sciences: Los Angeles (9-12) 17500 Burbank Blvd. Encino, CA 91361-1718 
# ### manually found lat/long via Google Maps: 34.172299, -118.514622
# 
# # fix outliers
# ## 2015-16
# ### Gateway to College, CDS code 38684780128876
# school_lat_long_2015_16$latitude[school_lat_long_2015_16$cds_code == 38684780128876] <- 37.724958
# school_lat_long_2015_16$longitude[school_lat_long_2015_16$cds_code == 38684780128876] <- -122.452911
#   
# school_lat_long_2016_17$latitude[school_lat_long_2015_16$cds_code == 38684780128876] <- 37.724958
# school_lat_long_2016_17$longitude[school_lat_long_2015_16$cds_code == 38684780128876] <- -122.452911
# 
# ## 2016-17
# ### Academy of Arts and Sciences: Los Angeles (9-12)
# school_lat_long_2015_16$latitude[school_lat_long_2015_16$cds_code == 19753090130781] <- 34.172299
# school_lat_long_2015_16$longitude[school_lat_long_2015_16$cds_code == 19753090130781] <- -118.514622
# 
# school_lat_long_2016_17$latitude[school_lat_long_2015_16$cds_code == 19753090130781] <- 34.172299
# school_lat_long_2016_17$longitude[school_lat_long_2015_16$cds_code == 19753090130781] <- -118.514622

```


```{r}


# # pull latitude from Long Valley record with it
# latitude_from_long_view_elementary <- 
#   schools_matched_by_cds_code_only %>% 
#   filter(cds_school_code == "6010763") %>%  # filter to Long Valley cds code
#   filter(!(latitude == "No Data")) %>%  # filter to the one with lat/long
#   pull(latitude)  # pull latitude as value

# # pull longitude from Long Valley record with it
# longitude_from_long_view_elementary <- 
#   schools_matched_by_cds_code_only %>% 
#   filter(cds_school_code == "6010763") %>%  # filter to Long Valley cds code
#   filter(!(latitude == "No Data")) %>%  # filter to the one with lat/long
#   pull(longitude)  # pull longitude as value

```



```{r make tibbles for 2016-2017 and 2017-2018}

# load relevant files
## 2016-17 enrollment
load(
  file = 
    file.path(
      "intermediate_data", 
      "school_enrollment_2016_17_working_from_raw.rdata"
    )
)

## 2017-18 enrollment
load(
  file = 
    file.path(
      "intermediate_data", 
      "school_enrollment_2017_18_working_from_raw.rdata"
    )
)

## school addresses
load(
  file = 
    file.path(
      "intermediate_data", 
      "public_school_directory_working_from_raw.rdata"
    )
)

# load function to make variable names snake case
load(
  file = 
    file.path(
      "functions", 
      "column_name_fixer.rdata"
    )
)

# load air data file
load(
  file = 
    file.path(
      "intermediate_data", 
      "air_cropped.rdata"
    )
)

# fix variable names
school_enrollment_2016_17_working <- 
  column_name_fixer(school_enrollment_2016_17_working_from_raw)

school_enrollment_2017_18_working <- 
  column_name_fixer(school_enrollment_2017_18_working_from_raw)

public_school_directory_working <- 
  column_name_fixer(public_school_directory_working_from_raw) %>% 
  rename(cds_code = cdscode)

# get lat/longs from public school directory
school_lat_long <- 
  public_school_directory_working %>% 
  dplyr::select(cds_code, latitude, longitude)

# isolate schools with nonzero enrollment in 2016-17
school_nonzero_2016_17 <- 
  school_enrollment_2016_17_working %>% 
  filter(enr_total > 0)

# isolate schools with nonzero enrollment in 2016-17
school_nonzero_2017_18 <- 
  school_enrollment_2017_18_working %>% 
  filter(enr_total > 0)

# get cds codes for schools 2016-17
school_cds_codes_2016_17 <- 
  school_enrollment_2016_17_working %>% 
  dplyr::select(cds_code, school) %>% 
  unique()

# get cds codes for schools with nonzero enrollment in 2017-18
school_cds_codes_2017_18 <- 
  school_enrollment_2017_18_working %>% 
  dplyr::select(cds_code, school) %>% 
  unique()

# join school and latitude/longitude
school_lat_long_na_2016_17 <- 
  school_cds_codes_2016_17 %>% 
  left_join(school_lat_long, by = "cds_code")

school_lat_long_na_2017_18 <- 
  school_cds_codes_2017_18 %>% 
  left_join(school_lat_long, by = "cds_code")

# filter missing latitudes and longitudes
school_lat_long_2016_17 <- 
  school_lat_long_na_2016_17 %>% 
  filter(!is.na(latitude)) %>% 
  filter(!is.na(longitude)) %>% 
  filter(longitude != "No Data") %>% 
  mutate(latitude = as.numeric(latitude), 
         longitude = as.numeric(longitude))
  
school_lat_long_2017_18 <- 
  school_lat_long_na_2017_18 %>% 
  filter(!is.na(latitude)) %>% 
  filter(!is.na(longitude)) %>% 
  filter(longitude != "No Data") %>% 
  mutate(latitude = as.numeric(latitude), 
         longitude = as.numeric(longitude))



# save files
save(
  public_school_directory_working,
  file =
    file.path(
      "intermediate_data",
      "public_school_directory_working.rdata"
    )
)

save(
  school_enrollment_2016_17_working,
  file =
    file.path(
      "intermediate_data",
      "school_enrollment_2016_17_working.rdata"
    )
)

save(
  school_enrollment_2017_18_working,
  file =
    file.path(
      "intermediate_data",
      "school_enrollment_2017_18_working.rdata"
    )
)

save(
  school_nonzero_2016_17, 
  file = 
    file.path(
      "intermediate_data", 
      "school_nonzero_2016_17.rdata"
    )
)

save(
  school_nonzero_2017_18, 
  file = 
    file.path(
      "intermediate_data", 
      "school_nonzero_2017_18.rdata"
    )
)

save(
  school_cds_codes_2016_17, 
  file = 
    file.path(
      "intermediate_data", 
      "school_cds_codes_2016_17.rdata"
    )
)

save(
  school_cds_codes_2017_18, 
  file = 
    file.path(
      "intermediate_data", 
      "school_cds_codes_2017_18.rdata"
    )
)

save(
  school_lat_long, 
  file = 
    file.path(
      "intermediate_data", 
      "school_lat_long.rdata"
    )
)

save(
  school_lat_long_na_2016_17,
  file =
    file.path(
      "intermediate_data",
      "school_lat_long_na_2016_17.rdata"
    )
)
  
save(
 school_lat_long_na_2017_18,
  file =
    file.path(
      "intermediate_data",
      "school_lat_long_na_2017_18.rdata"
    )
)

save(
  school_lat_long_2016_17_sf,
  file =
    file.path(
      "intermediate_data",
      "school_lat_long_2016_17_sf.rdata"
    )
)

save(
  school_lat_long_2017_18_sf,
  file =
    file.path(
      "intermediate_data",
      "school_lat_long_2017_18_sf.rdata"
    )
)

save(
  school_data_2016_17_sf, 
  file = 
    file.path(
      "intermediate_data",
      "school_data_2016_17_sf.rdata"
    )
)

save(
  school_data_2017_18_sf, 
  file = 
    file.path(
      "intermediate_data",
      "school_data_2017_18_sf.rdata"
    )
)

# plot(school_lat_long_2016_17_sf)
# plot(school_lat_long_2017_18_sf)

# remove all objects from the environment
rm(list = ls(all.names = TRUE))

```


```{r school data cleaning 2016-17}

# number of schools in 2016-17 enrollment data
load( 
  file = 
    file.path(
      "intermediate_data", 
      "school_enrollment_2016_17_working.rdata"
    )
)

unique_schools_enrollment <- 
  length(unique(school_enrollment_2016_17_working$cds_code))

# number of schools in directory
load(
  file = 
    file.path(
      "intermediate_data", 
      "public_school_directory_working.rdata"
    )
)

unique_schools_directory <- 
  length(unique(public_school_directory_working$cds_code))

# number of schools with non-zero enrollments
load(
  file = 
    file.path(
      "intermediate_data", 
      "school_nonzero_2016_17.rdata"
    )
)

unique_schools_non_zero <- 
  length(unique(school_nonzero_2016_17$cds_code))

# number of schools with enrollment with valid latitude and longitude
load(
  file = 
    file.path(
      "intermediate_data", 
      "school_lat_long_2016_17_sf.rdata"
    )
)
  
unique_schools_with_lat_long <- 
  length(unique(school_lat_long_2016_17_sf$cds_code))

# final number of schools in dataset 
load(
  file = 
    file.path(
      "intermediate_data",
      "school_data_2016_17_sf.rdata"
    )
)

unique_school_data_final <- 
  length(unique(school_data_2016_17_sf$cds_code))

# get crs codes of schools without lat_longs
crs_codes_no_lat_long <- 
  setdiff(
    unique(school_data_2016_17_sf$cds_code), 
    unique(school_lat_long_2016_17_sf$cds_code)
  )

# pull those schools and look at them
load(
  file = 
    file.path(
      "intermediate_data",
      "public_school_directory_working.rdata"
    )
)

# isolate schools with no lat/long (cds_code, county, district, school)
# create school code independent of county and district
unique_schools_no_lat_long <- 
  school_enrollment_2016_17_working %>% 
  filter(cds_code %in% crs_codes_no_lat_long) %>% 
  select(
    cds_code, 
    county,
    district,
    school) %>% 
  unique() %>% 
  mutate(cds_school_code = 
           str_sub(cds_code, 
                   start = -7))

# exclude nonpublic and nonsectarian schools
unique_schools_no_nonsec <- 
  unique_schools_no_lat_long %>% 
  filter(!(school == "Nonpublic, Nonsectarian Schools"))

# find which schools missing lat/longs are in the directory
school_directory_no_lat_long <- 
  public_school_directory_working %>% 
  filter(cds_code %in% crs_codes_no_lat_long)  # (only two)

# simplify public school directory and 
# create school code independent of county and district
limited_public_school_directory <- 
  public_school_directory_working %>% 
  select(
    cds_code_dir = cds_code, 
    county, 
    school, 
    latitude, 
    longitude) %>% 
  mutate(cds_school_code = str_sub(cds_code_dir,  # this isolates the individual school code
                                   start = -7))

# match on cds code
schools_matched_by_cds_code_only <- 
  left_join(
    unique_schools_no_nonsec, 
    limited_public_school_directory, 
    by = c("cds_school_code"))

save(
  schools_matched_by_cds_code_only, 
  file = 
    file.path(
      "intermediate_data", 
      "schools_matched_by_cds_code_only.rdata"
    )
)  

# clean THE LAST THREE

# clean Long Valley by removing version without lat/longs
schools_no_lat_long_long_valley_fix <- 
  schools_matched_by_cds_code_only %>% 
  filter(!(cds_school_code == "6010763" &  # remove no-data long view record
             latitude == "No Data"))  

# pull cds codes for the directory from the two remaining w/o lat/longs
cds_codes_last_two <- 
  schools_no_lat_long_long_valley_fix %>% 
  filter(latitude == "No Data") %>%  # filter to those w/o lat/longs
  pull(cds_code_dir)  # pull the cds code in the directory

# pull directory records for last two for annoyingly manual geocoding
addresses_last_two <- 
  public_school_directory_working %>% 
  filter(cds_code %in% cds_codes_last_two) %>% 
  select(cds_code_dir = cds_code,  # change name of cds_code 
         school, 
         street, 
         city, 
         state, 
         zip) %>% 
  mutate(address_geocode =  # put entire address in one column for google
           str_c(street, 
                 ", ", 
                 city, 
                 ", ", 
                 state, 
                 " ", 
                 zip)
  )

# geocoding time!
geocoded_lat_longs_last_two <-
  addresses_last_two %>%
  mutate_geocode(
    location = address_geocode
  ) 

# make limited dataset
geocoded_simple <- 
  geocoded_lat_longs_last_two %>% 
  select(school_geo = school,  # rename variables to show that they came from the geo dataset
         cds_code_geo = cds_code_dir, 
         lon_geo = lon, 
         lat_geo = lat)

# add geocoded lat/longs
schools_missing_lat_long_fixed <- 
  schools_no_lat_long_long_valley_fix %>% 
  left_join(geocoded_simple, 
            by = c("cds_code" = "cds_code_geo")) %>%  
  mutate(geo_source = "small_cds",  # add column to tibble for lat-long source
         geo_source = replace(geo_source, !is.na(lon_geo), "google"), 
         longitude = ifelse(longitude == "No Data", lon_geo, longitude), 
         latitude = ifelse(latitude == "No Data", lat_geo, latitude)
  ) %>% 
  select(man_cds_code = cds_code, 
         man_longitude = longitude, 
         man_latitude = latitude, geo_source)

# single schools from school_enrollment_2016_17_working 
# (includes those sans enrollment)

# make full dataset
school_clean <- 
  school_enrollment_2016_17_working %>% 
  left_join(schools_missing_lat_long_fixed, 
            by = c("cds_code" = "man_cds_code"))
  
# unique schools
unique_schools_2016_17 <- 
  school_enrollment_2016_17_working %>% 
  select(cds_code, county, district, school) %>% 
  mutate(cds_school_code = str_sub(cds_code,  # this isolates the individual school code
                                   start = -7)) %>% 
  unique()  # each of these has a unique cds code

# check number of unique school cds codes
# (turns out only 0000000 and 0000001 aren't unique)
sum(table(unique_schools_2016_17$cds_school_code) - 1)

# get lat/longs from public school directory
school_lat_long <- 
  public_school_directory_working %>% 
  dplyr::select(cds_code, latitude, longitude) %>% 
  mutate(cds_school_code = str_sub(cds_code,  # this isolates the individual school code
                                   start = -7))

length(unique(school_lat_long$cds_school_code))

unique_schools_all_lat_long <- 
  unique_

  
  
  

  
  

# # remove all objects from the environment
# rm(list = ls(all.names = TRUE))

```


```{r}

# check number of unique school cds codes
# (turns out only 0000000 and 0000001 aren't unique)
sum(table(unique_schools_2016_17$cds_school_code) - 1)

# get lat/longs from public school directory
school_lat_long <- 
  public_school_directory_working %>% 
  dplyr::select(cds_code, latitude, longitude) %>% 
  mutate(cds_school_code = str_sub(cds_code,  # this isolates the individual school code
                                   start = -7))

length(unique(school_lat_long$cds_school_code))

  

  # isolate schools with nonzero enrollment in 2016-17
school_nonzero_2016_17 <- 
  school_enrollment_2016_17_working %>% 
  filter(enr_total > 0)

```

